<a href="https://colab.research.google.com/github/SAI514133/SAI-TEJA/blob/main/array1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
arry =np.array([2,5,3,7,3])
print(arry)
print(type(arry))


[2 5 3 7 3]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
arry = np.array([[2,5],[4,2]])
arry1 = np.array([[2,5,4,2],[4,2,1,0]])
arry2 = np.array([[2,5,4],[4,2,5],[6,7,8]])
print(arry)
print(arry1)
print(arry2)



[[2 5]
 [4 2]]
[[2 5 4 2]
 [4 2 1 0]]
[[2 5 4]
 [4 2 5]
 [6 7 8]]


In [13]:
import numpy as np
arry1 = np.array([1,3,4,5,6])
arry2 = np.array([2,6,3,4,8])
print(arry1)
print(np.add(arry2,arry1))
print(np.subtract(arry2,arry1))
print(np.multiply(arry2,arry1))
print(np.divide(arry2,arry1))
print(type(arry))

[1 3 4 5 6]
[ 3  9  7  9 14]
[ 1  3 -1 -1  2]
[ 2 18 12 20 48]
[2.         2.         0.75       0.8        1.33333333]
<class 'numpy.ndarray'>
